/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type {VersionCommit} from './github/types';

/** Commits generated by pre-commit.ci are useful history, but not useful review steps. */
const PRE_COMMIT_CI_TITLE = /^\[pre-commit\.ci\]\s*auto[- ]?fixes\b/i;
const PRE_COMMIT_CI_AUTHOR = /\bpre-commit\.ci(?:\[bot\])?\b/i;

export function isAutomatedCommit(commit: Pick<VersionCommit, 'author' | 'title'>): boolean {
  return (
    PRE_COMMIT_CI_TITLE.test(commit.title.trim()) ||
    (commit.author != null && PRE_COMMIT_CI_AUTHOR.test(commit.author))
  );
}

/** Commits that should be included in the normal commit-by-commit review flow. */
export function isReviewableCommit(commit: VersionCommit): boolean {
  return commit.parents.length <= 1 && !isAutomatedCommit(commit);
}
