version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /oauth-worker
    schedule:
      interval: weekly
    groups:
      wrangler:
        patterns: ['wrangler']

  - package-ecosystem: npm
    directory: /mcp-worker
    schedule:
      interval: weekly
    groups:
      mcp-worker:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
